/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#7C4DFF",
        secondary: "#448AFF",
        accent: "#26A69A",
        background: "#08080C",
        status: {
          strong: "#4ADE80",
          average: "#F59E0B",
          weak: "#EF4444",
        },
        "surface": "#0e0e12",
        "surface-dim": "#0e0e12",
        "surface-bright": "#2c2b32",
        "surface-variant": "#25252b",
        "surface-container": "#19191e",
        "surface-container-low": "#131318",
        "surface-container-high": "#1f1f25",
        "surface-container-highest": "#25252b",
        "surface-container-lowest": "#000000",
        "on-surface": "#f3eff6",
        "on-surface-variant": "#acaab0",
        "on-primary": "#340090",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#32008a",
        "on-primary-container": "#280072",
        "on-background": "#f3eff6",
        "outline": "#76757a",
        "outline-variant": "#48474c",
        "primary-container": "#a98fff",
        "primary-dim": "#7e51ff",
        "primary-fixed": "#a98fff",
        "inverse-primary": "#6834eb",
        "error": "#ff6e84",
        "error-container": "#a70138",
        "on-error": "#490013",
        "surface-tint": "#b6a0ff",
      },
      fontFamily: {
        headline: ["Sora", "sans-serif"],
        body: ["Sora", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        sora: ["Sora", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      animation: {
        shimmer: "shimmer 8s infinite linear",
        glow: "glow 3s infinite alternate",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        glow: {
          "0%": { boxShadow: "0 0 5px rgba(124, 77, 255, 0.2), 0 0 10px rgba(124, 77, 255, 0.1)" },
          "100%": { boxShadow: "0 0 20px rgba(124, 77, 255, 0.4), 0 0 40px rgba(124, 77, 255, 0.2)" },
        },
      },
    },
  },
  plugins: [],
};
